
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-01
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-01
pull_requests: [{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-visibility","number":28,"title":"yl - Increase Visibility of the Course Details Page","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/28"},{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-refactor-csv-download","number":27,"title":"nn - refactor csv download for enrollment data","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/27"}]
