
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-01
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-01
pull_requests: [{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-paginate-jobs-frontend","number":38,"title":"wc - add frontend component for searching paginated jobs","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/38"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-paginate-jobs-backend","number":37,"title":"wc - modify backend endpoint for paginated jobs","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/37"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-no-courses-feedback","number":35,"title":"wc - added feedback when no courses are found","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/35"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-Remove-GradeHistory-Eslint-Exception","number":34,"title":"jv -  Remove GradeHistory Eslint Exception","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/34"},{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":"Yi Lin"},"headRefName":"yl-reintroduce","number":29,"title":"yl - reintroduce react eslint rules","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/29"}]
