
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-01
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-01
pull_requests: [{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-refactor-OurPagination","number":43,"title":"jv - REFACTOR: OurPagination has multiple levels of useState that may be unnecessary","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/43"},{"author":{"id":"U_kgDOCO5ODw","is_bot":false,"login":"noahzlouie","name":"Noah Louie"},"headRefName":"nl-userstable-pg-backend","number":42,"title":"nl - added backendpoint for usertable pagination","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-01/pull/42"}]
